InterProcessCourier: ipcourier Namespace Reference
ipcourier Namespace Reference
Base namespace of the library.
Data Structures
struct Error
Represents a generic error structure within the InterProcessCourier library.
class SyncClient
A synchronous client for inter-process communication using Protocol Buffers over Unix Domain Sockets.
struct SyncClientOptions
Structure to hold various configuration options for the SyncClient.
class SyncServer
A synchronous server for inter-process communication using Protocol Buffers over Unix Domain Sockets.
Concepts
concept IsEnum
Concept to check if a type is an enumeration.
concept IsDerivedFromProtoMessage
Concept to ensure template types derive from the Protocol Buffer Message base class.
Typedefs
template<typename SuccessType>
using ProtobufToolResult = std::expected<SuccessType, Error<ProtoPayloadParseError> >
Type alias for the result of Protocol Buffer tool operations.
using BaseProtoType = google::protobuf::Message
Type alias for a base type of all Protocol Buffer messages.
using NoMessage = google::protobuf::Empty
Type alias for an empty protobuf message.
using SerializedProtoPayload = std::string
Type alias for serialized protocol buffer payload.
template<typename SuccessType>
using SyncClientResult = std::expected<SuccessType, Error<SyncClientError> >
Type alias for the result of synchronous client operations.
template<typename SuccessType>
using SyncServerResult = std::expected<SuccessType, Error<SyncServerError> >
Type alias for the result of synchronous server operations.
Enumerations
enum class ProtoPayloadParseError { InvalidFormat , TypeMismatch , DeserializationFailed }
Error codes for Protocol Buffer payload parsing operations.
enum class SyncClientError {
UnknownError , BadRequestToResponsePair , UnableToConnectToServer , UnableToSendMessage ,
UnableToReceiveMessage , UnableToParseReturnedProto
}
Enumeration of specific error codes for the synchronous client.
enum class SyncServerError {
UnknownError , HandlerNotRegistered , RuntimeError , UnableToDeserializeMessage ,
UnableToSerializeMessage
}
Enumeration of specific error codes for the synchronous server.
Functions
SerializedProtoPayload createProtoPayload (std::string_view type_name, std::string_view serialized_data)
Creates a formatted payload string from type name and serialized data.
template<IsDerivedFromProtoMessage ProtoType>
SerializedProtoPayload makePayloadFromProto (const ProtoType &message)
Serializes a Protocol Buffer message into a payload string.
template<IsDerivedFromProtoMessage ProtoType>
ProtobufToolResult< ProtoType > makeProtoFromPayload (const SerializedProtoPayload &payload)
Deserializes a payload string back into a Protocol Buffer message.
std::string getLibraryVersion ()
Gets the version string of the InterProcessCourier library.
Detailed Description
Base namespace of the library.
Typedef Documentation
BaseProtoType
using ipcourier::BaseProtoType = google::protobuf::Message
Type alias for a base type of all Protocol Buffer messages.
Definition at line 58 of file ProtobufTools.hpp.
NoMessage
using ipcourier::NoMessage = google::protobuf::Empty
Type alias for an empty protobuf message.
Definition at line 61 of file ProtobufTools.hpp.
ProtobufToolResult
template<typename SuccessType> using ipcourier::ProtobufToolResult = std::expected<SuccessType, Error<ProtoPayloadParseError> >
Type alias for the result of Protocol Buffer tool operations.
This alias represents an std::expected type where success is indicated by SuccessType and failure by an Error object containing a ProtoPayloadParseError.
Template Parameters
SuccessType The type returned on successful operation.
Definition at line 55 of file ProtobufTools.hpp.
SerializedProtoPayload
using ipcourier::SerializedProtoPayload = std::string
Type alias for serialized protocol buffer payload.
Definition at line 71 of file ProtobufTools.hpp.
SyncClientResult
template<typename SuccessType> using ipcourier::SyncClientResult = std::expected<SuccessType, Error<SyncClientError> >
Type alias for the result of synchronous client operations.
This alias represents an std::expected type where success is indicated by SuccessType and failure by an Error object containing a SyncClientError.
Template Parameters
SuccessType The type returned on successful operation.
Definition at line 56 of file SyncClient.hpp.
SyncServerResult
template<typename SuccessType> using ipcourier::SyncServerResult = std::expected<SuccessType, Error<SyncServerError> >
Type alias for the result of synchronous server operations.
This alias represents an std::expected type where success is indicated by SuccessType and failure by an Error object containing a SyncServerError.
Template Parameters
SuccessType The type returned on successful operation.
Definition at line 57 of file SyncServer.hpp.
Enumeration Type Documentation
ProtoPayloadParseError
enum class ipcourier::ProtoPayloadParseError strong
Error codes for Protocol Buffer payload parsing operations.
Enumerator
InvalidFormat
Missing or malformed delimiter in payload string.
TypeMismatch
Type name in the payload doesn't match an expected Protocol Buffer type.
DeserializationFailed
Protocol Buffer parsing failed (corrupt data, wrong format, etc.)
Definition at line 40 of file ProtobufTools.hpp.
SyncClientError
enum class ipcourier::SyncClientError strong
Enumeration of specific error codes for the synchronous client.
Enumerator
UnknownError
An unspecified error occurred.
BadRequestToResponsePair
The requested Protocol Buffer type pair (request/response) is not registered.
UnableToConnectToServer
The client failed to establish a connection with the server.
UnableToSendMessage
The client failed to send a message to the server.
UnableToReceiveMessage
The client failed to receive a message from the server.
UnableToParseReturnedProto
The client received a message but failed to parse it into a Protocol Buffer.
Definition at line 38 of file SyncClient.hpp.
SyncServerError
enum class ipcourier::SyncServerError strong
Enumeration of specific error codes for the synchronous server.
Enumerator
UnknownError
An unspecified error occurred.
HandlerNotRegistered
No handler is registered for the received Protocol Buffer message type.
RuntimeError
An error occurred during the execution of a message handler.
UnableToDeserializeMessage
The server failed to deserialize an incoming message into a Protocol Buffer.
UnableToSerializeMessage
The server failed to serialize a response Protocol Buffer message.
Definition at line 40 of file SyncServer.hpp.
Function Documentation
createProtoPayload()
SerializedProtoPayload ipcourier::createProtoPayload (std::string_view type_name, std::string_view serialized_data)
Creates a formatted payload string from type name and serialized data.
Creates a payload in the format "type_name:serialized_data" where the colon serves as a delimiter between the Protocol Buffer type identifier and the actual serialized message data.
Parameters
type_name The full name of the Protocol Buffer message type
serialized_data The serialized Protocol Buffer message data
Returns
SerializedProtoPayload The formatted payload string
Referenced by makePayloadFromProto().
getLibraryVersion()
std::string ipcourier::getLibraryVersion ()
Gets the version string of the InterProcessCourier library.
Returns the current version of the InterProcessCourier library at compile time. The version follows semantic versioning (MAJOR.MINOR.PATCH) format.
Returns
The library version string (e.g., "1.2.3")
makePayloadFromProto()
template<IsDerivedFromProtoMessage ProtoType> SerializedProtoPayload ipcourier::makePayloadFromProto (const ProtoType & message)
Serializes a Protocol Buffer message into a payload string.
Takes a Protocol Buffer message, serializes it to binary format, and creates a payload string that includes both the message type information and the serialized data. The resulting payload can be transmitted over inter-process communication channels and later deserialized back to the original message type.
Template Parameters
ProtoType The Protocol Buffer message type (must derive from google::protobuf::Message)
Parameters
message The Protocol Buffer message to serialize
Returns
std::string The formatted payload string containing type info and serialized data
See also
makeProtoFromPayload for the reverse operation
Definition at line 101 of file ProtobufTools.hpp.
References createProtoPayload().
Referenced by ipcourier::SyncServer::registerHandler(), and ipcourier::SyncClient::sendRequest().
makeProtoFromPayload()
template<IsDerivedFromProtoMessage ProtoType> ProtobufToolResult< ProtoType > ipcourier::makeProtoFromPayload (const SerializedProtoPayload & payload)
Deserializes a payload string back into a Protocol Buffer message.
Parses a payload string created by makePayloadFromProto() and reconstructs the original Protocol Buffer message. The function validates that the type information in the payload matches the expected message type before attempting deserialization.
Template Parameters
ProtoType The expected Protocol Buffer message type (must derive from Message)
Parameters
payload The payload string containing type info and serialized data
Returns
ProtobufToolResult<ProtoType> Either the deserialized message or an error code indicating the failure reason
Return values
ProtoType Successfully deserialized Protocol Buffer message
InvalidFormat The payload string doesn't contain the expected delimiter
TypeMismatch The type name in the payload doesn't match ProtoType
DeserializationFailed The Protocol Buffer parsing failed
See also
makePayloadFromProto for the reverse operation
Example:
// Assuming MyMessage is a defined Protocol Buffer message
const SerializedProtoPayload payload = "my.package.MyMessage:some_binary_data";
const auto result = ipcourier::makeProtoFromPayload<MyMessage>(payload);
if (result) {
MyMessage msg = *result;
// Use msg
} else {
// Handle result.error()
}
Definition at line 141 of file ProtobufTools.hpp.
References DeserializationFailed, InvalidFormat, and TypeMismatch.
Referenced by ipcourier::SyncClient::sendRequest().